---
title: "Analyzing effective probes data"
author: "Josef Klafka and Allyson Ettinger"
date: "7/29/2019"
output: html_document
---

```{r setup, include=FALSE}
libra
library(tidyverse)
library(here)

knitr::opts_chunk$set(echo = TRUE)
```

```{r data pipeline}
read_results <- function(filename) {
  read_csv(here(filename), 
                    col_names = c("rep", "word", "score"))
}


number <- read_csv(here("scil/number.csv"))
number$word <- rep(c("the (subj)", "cat", "chased", "the (obj)", "rats"), times = 4) %>% 
  factor(levels = c("the (subj)", "cat", "chased", "the (obj)", "rats"))
sn <- read_results("scil/subject_number.csv") %>%
  mutate(target = "subject")
sn$word <- rep(c("the (subj)", "cat", "chased", "the (obj)", "rats"), times = 4) %>% 
  factor(levels = c("the (subj)", "cat", "chased", "the (obj)", "rats"))

on <- read_results("scil/object_number.csv") %>%
  mutate(target = "object")
on$word <- rep(c("the (subj)", "cat", "chased", "the (obj)", "rats"), times = 4) %>% 
  factor(levels = c("the (subj)", "cat", "chased", "the (obj)", "rats"))
number <- sn %>% bind_rows(on)

number %>% 
  filter(target == "subject") %>%
  ggplot(aes(x = `Probed word position`, y = Accuracy, color = Embedder, group = Embedder)) + 
  geom_point() + 
  geom_line() 


og <- read_results("scil/object_gender.csv") %>% 
  mutate(target = "object")
og$word <- rep(c("the (subj)", "cat", "chased", "the (obj)", "rats"), times = 4) %>% 
  factor(levels = c("the (subj)", "cat", "chased", "the (obj)", "rats"))
sg <- read_results("scil/subject_gender.csv") %>%
  mutate(target = "subject")
sg$word <- rep(c("the (subj)", "cat", "chased", "the (obj)", "rats"), times = 4) %>% 
  factor(levels = c("the (subj)", "cat", "chased", "the (obj)", "rats"))
gender <- sg %>% bind_rows(og)

oa <- read_results("scil/object_animacy.csv")


sa <- read_results("scil/subject_animacy.csv")

# plotting the data

```

```{r tests}
res <- subject %>% 
  filter(rep == "bert", word == 4) %>% slice(1, 3) %>% # for example
  select(score) %>% 
  mutate(score = score * 1000) %>% 
  mutate(total = 1000) %>% 
  t()

res %>% prop.test()
```